### PR TITLE
Add logo.

### PR DESCRIPTION
**Pull request by fnordahl**
Albeit not perfect, I thought it would be fun to have a logo for the project.

The OVN logo comes from [0], the radiant above comes from [1] under a Creative Commons Attribution-Share Alike license.

0: https://github.com/ovn-org/ovn/blob/main/Documentation/_static/logo.png
1: https://commons.wikimedia.org/wiki/File:Heating-Radiator.svg

Signed-off-by: Frode Nordahl <frode.nordahl@canonical.com>

### CODE REVIEW

**Comment by dceara** [comment]
This is awesome, thanks a lot!

**Comment by dceara** [comment]
I wonder if we should wait until we decide whether this repo should be transferred to ovn-org.

**Comment by dceara** [comment]
CC: @igsilya

**Comment by dceara** [comment]
> As an alternative, we could re-format the docs into rST. :)

Maybe.  I'm no rST (or Markdown) expert though.

**Comment by dceara** [comment]
> > @fnordahl I was playing a bit with it, trying to add the logo to the readme. What do you of [this way of displaying it in the readme](https://github.com/dceara/ovn-heater/commit/0d71e1aec4515f7bddff5b9026087bac4d3b0ac7)? I have minimal markdown knowledge so there might be better ways of doing this. :)
> 
> Cool, the only alternative I know of would be to use Markdown tables, but to do alignment etc in tables we would need to resort to HTML anyway, so I think your proposal is good, happy to fold it into the PR if you want.
> 

That sounds good to me, thanks!

> Found some stackoverflow example claiming something like `logl{width=35px}` should work, but that does not appear to work for me, at least not on gist nor in this comment.

Yeah, this didn't seem to work.

**Comment by igsilya** [comment]
> > As an alternative, we could re-format the docs into rST. :)
> 
> Maybe. I'm no rST (or Markdown) expert though.

It has a specialized `.. image` directive: https://docutils.sourceforge.io/docs/ref/rst/directives.html#images

**Comment by igsilya** [comment]
> > > > As an alternative, we could re-format the docs into rST. :)
> > > 
> > > 
> > > Maybe. I'm no rST (or Markdown) expert though.
> > 
> > 
> > It has a specialized `.. image` directive: https://docutils.sourceforge.io/docs/ref/rst/directives.html#images
> 
> I think if we do that it probably deserves a separate PR.

Sure I wasn't suggesting to do that right here.

**Comment by dceara** [comment]
Quoting the Licensing section of https://commons.wikimedia.org/wiki/File:Heating-Radiator.svg:
```
You are free:

        to share – to copy, distribute and transmit the work
        to remix – to adapt the work

    Under the following conditions:

        attribution – You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
        share alike – If you remix, transform, or build upon the material, you must distribute your contributions under the [same or compatible license](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses) as the original.
```

Should we add a license-related section to our README?  Or should we add the logo to a separate directory with its own README indicating/linking to the original author and license?

I'm not sure what the best option is..

Thoughts?

**Comment by fnordahl** [comment]
> Quoting the Licensing section of https://commons.wikimedia.org/wiki/File:Heating-Radiator.svg:
> 
> ```
>     You are free:
> 
>         to share – to copy, distribute and transmit the work
>         to remix – to adapt the work
> 
>     Under the following conditions:
> 
>         attribution – You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
>         share alike – If you remix, transform, or build upon the material, you must distribute your contributions under the [same or compatible license](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses) as the original.
> ```
> 
> Should we add a license-related section to our README? Or should we add the logo to a separate directory with its own README indicating/linking to the original author and license?
> 
> I'm not sure what the best option is..
> 
> Thoughts?

Good question! I guess an alternative could also be to use something like [the copyright file in OVS](https://github.com/openvswitch/ovs/blob/master/debian/copyright.in)?

**Comment by dceara** [comment]
> > Should we add a license-related section to our README? Or should we add the logo to a separate directory with its own README indicating/linking to the original author and license?
> > I'm not sure what the best option is..
> > Thoughts?
> 
> Good question! I guess an alternative could also be to use something like [the copyright file in OVS](https://github.com/openvswitch/ovs/blob/master/debian/copyright.in)?

Thanks for the pointer!  I think that should be fine.  But, thinking that ovn-heater will probably never have as much contributors as OVS does, should we just build a static copyright file (replacing the current AUTHORS file we have)?

And as a follow up question: do you feel OK contributing this part of the change too or shall I put up a separate PR for it?

**Comment by fnordahl** [comment]
> > > Should we add a license-related section to our README? Or should we add the logo to a separate directory with its own README indicating/linking to the original author and license?
> > > I'm not sure what the best option is..
> > > Thoughts?
> > 
> > 
> > Good question! I guess an alternative could also be to use something like [the copyright file in OVS](https://github.com/openvswitch/ovs/blob/master/debian/copyright.in)?
> 
> Thanks for the pointer! I think that should be fine. But, thinking that ovn-heater will probably never have as many contributors as OVS does, should we just build a static copyright file (replacing the current AUTHORS file we have)?
> 
> And as a follow up question: do you feel OK contributing this part of the change too or shall I put up a separate PR for it?

Cool, I'm fine with adding it as part of this PR.

**Comment by fnordahl** [comment]
> > > > Should we add a license-related section to our README? Or should we add the logo to a separate directory with its own README indicating/linking to the original author and license?
> > > > I'm not sure what the best option is..
> > > > Thoughts?
> > > 
> > > 
> > > Good question! I guess an alternative could also be to use something like [the copyright file in OVS](https://github.com/openvswitch/ovs/blob/master/debian/copyright.in)?
> > 
> > 
> > Thanks for the pointer! I think that should be fine. But, thinking that ovn-heater will probably never have as many contributors as OVS does, should we just build a static copyright file (replacing the current AUTHORS file we have)?
> > And as a follow up question: do you feel OK contributing this part of the change too or shall I put up a separate PR for it?
> 
> Cool, I'm fine with adding it as part of this PR.

As part of tracking down the original author, I also found the original SVG from blp, so I improved the creation!

I also took the liberty of proposing a re-license, pending blp's permission here: https://mail.openvswitch.org/pipermail/ovs-dev/2023-March/402845.html

**Comment by blp** [comment]
This is great, I like it very much :-)

**Comment by blp** [comment]
I approve the relicensing.

**Comment by dceara** [comment]
Thanks @fnordahl, @blp, @igsilya!

**Pull request merged**
